# Generated by Django 4.0.4 on 2022-06-01 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anneeacademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=10)),
                ('idan', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('lieu', models.CharField(blank=True, max_length=50, null=True)),
                ('idetud', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('tutelle', models.CharField(blank=True, max_length=50, null=True)),
                ('parcours', models.CharField(blank=True, max_length=50, null=True)),
                ('idfor', models.IntegerField()),
                ('campus', models.CharField(blank=True, max_length=40, null=True)),
                ('domain', models.CharField(blank=True, max_length=50, null=True)),
                ('filiere', models.CharField(blank=True, max_length=50, null=True)),
                ('detailformation', models.CharField(blank=True, max_length=50, null=True)),
                ('periode', models.CharField(blank=True, max_length=50, null=True)),
                ('niveau', models.CharField(blank=True, max_length=50, null=True)),
                ('cycle', models.CharField(blank=True, max_length=50, null=True)),
                ('idf', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idins', models.IntegerField()),
                ('idf', models.IntegerField()),
                ('idfor', models.IntegerField()),
                ('idan', models.IntegerField()),
                ('inslogin', models.CharField(max_length=50, null=True)),
                ('insmdp', models.CharField(max_length=50, null=True)),
                ('tof', models.ImageField(blank=True, null=True, upload_to='')),
                ('anneeacademique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Moncompte.anneeacademique', verbose_name='anneeacademique')),
                ('etudiant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to='Moncompte.etudiant')),
                ('formationins', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Moncompte.formation', verbose_name='formation')),
            ],
        ),
        migrations.CreateModel(
            name='profmatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=50)),
                ('idsem', models.IntegerField()),
                ('ue', models.CharField(max_length=50)),
                ('codeue', models.CharField(blank=True, max_length=15, null=True)),
                ('creditue', models.IntegerField()),
                ('moduleue', models.CharField(blank=True, max_length=50, null=True)),
                ('idue', models.IntegerField()),
                ('idfor', models.IntegerField()),
                ('matiere', models.CharField(max_length=50)),
                ('enseignant', models.CharField(blank=True, max_length=50, null=True)),
                ('creditpm', models.IntegerField()),
                ('codepm', models.CharField(blank=True, max_length=15, null=True)),
                ('idpm', models.IntegerField()),
                ('formationpm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Moncompte.formation', verbose_name='formation')),
            ],
        ),
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idpm', models.IntegerField()),
                ('idins', models.IntegerField()),
                ('moyesem', models.DecimalField(decimal_places=2, max_digits=2)),
                ('moyue', models.DecimalField(decimal_places=2, max_digits=2)),
                ('moypm', models.DecimalField(decimal_places=2, max_digits=2)),
                ('cc', models.DecimalField(decimal_places=2, max_digits=2)),
                ('examen', models.DecimalField(decimal_places=2, max_digits=2)),
                ('creditsem', models.IntegerField()),
                ('creditue', models.IntegerField()),
                ('creditpm', models.IntegerField()),
                ('decisionsem', models.CharField(max_length=10)),
                ('decisionue', models.CharField(max_length=10)),
                ('decisionpm', models.CharField(max_length=10)),
                ('sessionsem', models.CharField(max_length=15)),
                ('sessionue', models.CharField(max_length=15)),
                ('sessionpm', models.CharField(max_length=15)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Moncompte.inscription')),
                ('profmatiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Moncompte.profmatiere')),
            ],
        ),
        migrations.CreateModel(
            name='emplois_de_temps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=10)),
                ('idem', models.IntegerField()),
                ('hd', models.TimeField(blank=True, null=True)),
                ('hf', models.TimeField(blank=True, null=True)),
                ('anneeacademique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Moncompte.anneeacademique', verbose_name='anneeacademique')),
                ('profmatiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Moncompte.profmatiere', verbose_name='profmatiere')),
            ],
        ),
    ]
