# Generated by Django 4.0.4 on 2022-06-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moncompte', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscription',
            old_name='formationins',
            new_name='formation',
        ),
        migrations.RenameField(
            model_name='profmatiere',
            old_name='formationpm',
            new_name='formation',
        ),
        migrations.AlterField(
            model_name='notes',
            name='cc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='examen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='moyesem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='moypm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='moyue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
