# Generated by Django 4.0.4 on 2022-05-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moncompte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_login', models.CharField(max_length=50)),
                ('us_pass', models.CharField(max_length=50)),
            ],
        ),
    ]
