# Generated by Django 4.0.4 on 2022-05-18 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Moncompte', '0002_userprofil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userProfil',
        ),
        migrations.AddField(
            model_name='inscription',
            name='ins_login',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='ins_mdp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emplois_de_temps',
            name='anneeacademique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Moncompte.anneeacademique', verbose_name='anneeacademique'),
        ),
        migrations.AlterField(
            model_name='emplois_de_temps',
            name='profmatiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Moncompte.profmatiere', verbose_name='profmatiere'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='anneeacademique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anneeacademique', to='Moncompte.anneeacademique', verbose_name='anneeacademique'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='etudiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to='Moncompte.etudiant', verbose_name='etudiant'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='formation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formation', to='Moncompte.formation', verbose_name='formation'),
        ),
    ]
