# Generated by Django 4.0.4 on 2022-05-18 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Moncompte', '0003_delete_userprofil_inscription_ins_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='etudiant',
        ),
        migrations.AddField(
            model_name='inscription',
            name='etud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to='Moncompte.etudiant'),
        ),
    ]
