# Generated by Django 4.0.4 on 2022-05-20 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Moncompte', '0004_remove_inscription_etudiant_inscription_etud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscription',
            old_name='etud',
            new_name='etudiant',
        ),
        migrations.AlterField(
            model_name='anneeacademique',
            name='an_libelle',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='formasem',
            name='fsem_cycle',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='formasem',
            name='fsem_niveau',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='formasem',
            name='fsem_semestre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='formasue',
            name='formasem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Moncompte.formasem'),
        ),
    ]
