# Generated by Django 4.0.4 on 2022-05-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moncompte', '0005_rename_etud_inscription_etudiant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='for_niveau',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='for_campus',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='for_detailformation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='for_domain',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='for_filiere',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='for_parcours',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='for_periode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='for_tutelle',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
