# Generated by Django 4.0.4 on 2022-05-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moncompte', '0008_alter_emplois_de_temps_anneeacademique_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formation',
            old_name='ancien_idetail',
            new_name='idf',
        ),
        migrations.AddField(
            model_name='inscription',
            name='idf',
            field=models.IntegerField(blank=True, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
