# Generated by Django 4.0.4 on 2022-05-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moncompte', '0009_rename_ancien_idetail_formation_idf_inscription_idf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='ancienid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
