# Generated by Django 4.0.4 on 2022-05-28 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Moncompte', '0011_alter_etudiant_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idpm', models.IntegerField()),
                ('idins', models.IntegerField()),
                ('moyesem', models.DecimalField(decimal_places=2, max_digits=2)),
                ('moyue', models.DecimalField(decimal_places=2, max_digits=2)),
                ('moypm', models.DecimalField(decimal_places=2, max_digits=2)),
                ('creditsem', models.IntegerField()),
                ('creditue', models.IntegerField()),
                ('creditpm', models.IntegerField()),
                ('decisionsem', models.CharField(max_length=10)),
                ('decisionue', models.CharField(max_length=10)),
                ('decisionpm', models.CharField(max_length=10)),
                ('sessionsem', models.CharField(max_length=15)),
                ('sessionue', models.CharField(max_length=15)),
                ('sessionpm', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='formasue',
            name='formasem',
        ),
        migrations.RemoveField(
            model_name='notesemestre',
            name='formasem',
        ),
        migrations.RemoveField(
            model_name='notesemestre',
            name='inscription',
        ),
        migrations.RenameField(
            model_name='emplois_de_temps',
            old_name='ancienid',
            new_name='idem',
        ),
        migrations.RenameField(
            model_name='etudiant',
            old_name='ancienid',
            new_name='idetud',
        ),
        migrations.RenameField(
            model_name='formation',
            old_name='ancien_idfor',
            new_name='idfor',
        ),
        migrations.RenameField(
            model_name='profmatiere',
            old_name='ancienid',
            new_name='creditue',
        ),
        migrations.RemoveField(
            model_name='anneeacademique',
            name='ancienid',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='ancienid',
        ),
        migrations.RemoveField(
            model_name='profmatiere',
            name='formasue',
        ),
        migrations.AddField(
            model_name='anneeacademique',
            name='idan',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inscription',
            name='idan',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscription',
            name='idins',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscription',
            name='tof',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profmatiere',
            name='codeue',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profmatiere',
            name='cycle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profmatiere',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Moncompte.formation', verbose_name='formation'),
        ),
        migrations.AddField(
            model_name='profmatiere',
            name='idfor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profmatiere',
            name='idpm',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profmatiere',
            name='idsem',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profmatiere',
            name='idue',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profmatiere',
            name='moduleue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profmatiere',
            name='niveau',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profmatiere',
            name='semestre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profmatiere',
            name='ue',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscription',
            name='idf',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='formasem',
        ),
        migrations.DeleteModel(
            name='formasue',
        ),
        migrations.DeleteModel(
            name='notesemestre',
        ),
        migrations.AddField(
            model_name='notes',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Moncompte.inscription', verbose_name='inscription'),
        ),
        migrations.AddField(
            model_name='notes',
            name='profmatiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Moncompte.profmatiere', verbose_name='profmatiere'),
        ),
    ]
