# Generated by Django 4.0.4 on 2022-05-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moncompte', '0012_notes_remove_formasue_formasem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profmatiere',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='profmatiere',
            name='niveau',
        ),
        migrations.AddField(
            model_name='formation',
            name='cycle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
