# Generated by Django 4.0.4 on 2022-05-28 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Moncompte', '0013_remove_profmatiere_cycle_remove_profmatiere_niveau_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profmatiere',
            old_name='formation',
            new_name='formationpm',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='formation',
        ),
        migrations.AddField(
            model_name='inscription',
            name='formationins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Moncompte.formation', verbose_name='formation'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='idfor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscription',
            name='anneeacademique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Moncompte.anneeacademique', verbose_name='anneeacademique'),
        ),
    ]
